export const QUOTES = [
  // Work & Diligence
  "There is no substitute for hard work. — Thomas Edison",
  "The heights by great men reached and kept were not attained by sudden flight, but they, while their companions slept, were toiling upward in the night. — Henry Wadsworth Longfellow",
  "Opportunity is missed by most people because it is dressed in overalls and looks like work. — Thomas Edison",
  "Genius is one percent inspiration and ninety-nine percent perspiration. — Disputed",
  "Thinking is the hardest work there is, which is probably the reason why so few engage in it. — Henry Ford",
  "Pleasure in the job puts perfection in the work. — Aristotle",
  "Inspiration exists, but it has to find you working. — Pablo Picasso",
  "The mechanic, who wishes to do his work well, must first sharpen his tools. — Confucius",

  // Success & Achievement
  "Many of life's failures are people who did not realize how close they were to success when they gave up. — Thomas Edison",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "If you really look closely, most overnight successes took a long time. — Steve Jobs",
  "It is better to fail in originality than to succeed in imitation. — Herman Melville",
  "Big results require big ambitions. — Heraclitus",
  "There is nothing impossible to him who will try. — Alexander the Great",
  "Fortune favors the bold. — Virgil",

  // Perseverance & Resilience
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "If you can't fly then run, if you can't run then walk, if you can't walk then crawl. But whatever you do, you have to keep moving forward. — Martin Luther King Jr.",
  "You just can't beat the person who never gives up. — Babe Ruth",
  "We choose to go to the moon ..., because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one which we intend to win, and the others, too. — John F. Kennedy",
  "Failure is simply the opportunity to begin again, this time more intelligently. — Henry Ford",
  "The impediment to action advances action. What stands in the way becomes the way. — Marcus Aurelius",
  "Difficulties strengthen the mind, as labor does the body. — Seneca",
  "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult. — Seneca",
  "The greater the difficulty, the more glory in surmounting it. — Epicurus",
  "Yield not to disasters, but press onward the more bravely. — Virgil",
  "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
  "A gem cannot be polished without friction, nor a man perfected without trials. — Chinese Proverb",
  "Pearls don't lie on the seashore. If you want one, you must dive for it. — Chinese Proverb",
  "That which does not kill us makes us stronger. — Friedrich Nietzsche",
  "Vitality shows in not only the ability to persist but the ability to start over. — F. Scott Fitzgerald",
  "But man is not made for defeat. A man can be destroyed but not defeated. — Ernest Hemingway",
  "Money grows on the tree of persistence. — Japanese Proverb",
  "They can conquer who believe they can. — Virgil",
  "In the depth of winter, I finally learned that within me there lay an invincible summer. — Albert Camus",

  // Knowledge, Learning, & Wisdom
  "The more you learn, the more you earn. — Warren Buffett",
  "We cannot solve our problems with the same thinking we used when we created them. — Albert Einstein",
  "The man who does not read has no advantage over the man who cannot read. — Unknown",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "If you want to improve, be content to be thought foolish and stupid. — Epictetus",
  "No man was ever wise by chance. — Seneca",
  "The roots of education are bitter, but the fruit is sweet. — Aristotle",
  "To know what you know and what you do not know, that is true knowledge. — Confucius",
  "It is not enough to have a good mind; the main thing is to use it well. — René Descartes",
  "I am always doing that which I cannot do, in order that I may learn how to do it. — Pablo Picasso",
  "I hear and I forget. I see and I remember. I do and I understand. — Xunzi",
  "If you would not be forgotten, as soon as you are dead and rotten, either write things worth reading, or do things worth the writing. — Benjamin Franklin",

  // Creation, Design, & Innovation
  "Every act of creation is first an act of destruction. — Pablo Picasso",
  "To create something exceptional, your mindset must be relentlessly focused on the smallest detail. — Giorgio Armani",
  "Creation is a drug I cannot do without. — Cecil B. DeMille",
  "What we build, builds us. — Anonymous",
  "The secret of change is to focus all of your energy, not on fighting the old, but on building the new. — Socrates",
  "Nothing is built on stone; all is built on sand, but we must build as if the sand were stone. — Jorge Luis Borges",
  "Innovation distinguishes between a leader and a follower. — Steve Jobs",
  "Details matter, it's worth waiting to get it right. — Steve Jobs",
  "No great thing is created suddenly. — Epictetus",
  "To create is to live twice. — Albert Camus",
  "By believing passionately in something that still does not exist, we create it. — Nikos Kazantzakis",
  "Creativity takes courage. — Henri Matisse",
  "Great things are done by a series of small things brought together. — Vincent van Gogh",

  // Action & Execution
  "Action is the foundational key to all success. — Pablo Picasso",
  "Knowing is not enough; we must apply. Being willing is not enough; we must do. — Johann Wolfgang von Goethe",
  "If a man knows not to which port he sails, no wind is favorable. — Seneca",
  "The beginning is the most important part of the work. — Plato",
  "A journey of a thousand miles begins with a single step. — Lao Tzu",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "As you start to walk on the way, the way appears. — Jalal ad-Din Muhammad Rumi",
  "A path is made by walking on it. — Zhuangzi",
  "Commitment is an act, not a word. — Jean-Paul Sartre",
  "You've got to jump off cliffs all the time and build your wings on the way down. — Ray Bradbury",
  "The philosophers have only interpreted the world in various ways; the point is to change it. — Karl Marx",
  "The man who moves a mountain begins by carrying away small stones. — Confucius",

  // Character & Self—Mastery
  "The successful warrior is the average man, with laser—like focus. — Bruce Lee",
  "Quality means doing it right when no one is looking. — Henry Ford",
  "Waste no more time arguing about what a good man should be. Be one. — Marcus Aurelius",
  "To conquer oneself is the best and noblest victory. — Plato",
  "It is folly for a man to pray to the gods for that which he has the power to obtain by himself. — Epicurus",
  "Wheresoever you go, go with all your heart. — Confucius",
  "Man is nothing else but what he makes of himself. — Jean-Paul Sartre",
  "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self. — Disputed",
  "It takes something more than intelligence to act intelligently. — Fyodor Dostoevsky",
  "Courage is knowing what not to fear. — Plato",
  "We acquire a particular quality by constantly acting in a particular way. — Aristotle",
  "He who knows, does not speak. He who speaks, does not know. — Lao Tzu",

  // Perspective & Philosophy
  "Keep your eyes on the stars, and your feet on the ground. — Theodore Roosevelt",
  "Your time is limited, don't waste it living someone else's life. — Steve Jobs",
  "You have power over your mind — not outside events. Realize this, and you will find strength. — Marcus Aurelius",
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. — Marcus Aurelius",
  "Let each thing you would do, say, or intend, be like that of a dying person. — Marcus Aurelius",
  "Make the best use of what is in your power, and take the rest as it happens. — Epictetus",
  "In the midst of chaos, there is also opportunity. — Sun Tzu",
  "He who would learn to fly one day must first learn to stand and walk and run and climb and dance; one cannot fly into flying. — Friedrich Nietzsche",
  "No one can construct for you the bridge upon which precisely you must cross the stream of life, no one but you yourself alone. — Friedrich Nietzsche",
  "He who has a why to live for can bear almost any how. — Friedrich Nietzsche",
  "Life can only be understood backwards; but it must be lived forwards. — Søren Kierkegaard",
  "Every man takes the limits of his own field of vision for the limits of the world. — Arthur Schopenhauer",
  "Only those who will risk going too far can possibly find out how far one can go. — T.S. Eliot",
  "Beyond a certain point there is no return. This point has to be reached. — Franz Kafka",
  "You cannot create experience. You must undergo it. — Albert Camus",
  "Not everything that is faced can be changed, but nothing can be changed until it is faced. — James Baldwin",
  "Now is no time to think of what you do not have. Think of what you can do with what there is. — Ernest Hemingway",
  "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced. — Vincent van Gogh",
  "I am seeking, I am striving, I am in it with all my heart. — Vincent van Gogh",
]
